/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as ApiMarketPricesRouteImport } from './routes/api/market-prices'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiNewsIngestRouteImport } from './routes/api/news-ingest'
import { Route as ApiNewsIngestV2RouteImport } from './routes/api/news-ingest-v2'
import { Route as ApiTelegramPhotoRouteImport } from './routes/api/telegram-photo'
import { Route as ApiTelegramVideoRouteImport } from './routes/api/telegram-video'
import { Route as NSlugRouteImport } from './routes/n.$slug'
import { Route as ApiNewsIdRouteImport } from './routes/api/news.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketPricesRoute = ApiMarketPricesRouteImport.update({
  id: '/api/market-prices',
  path: '/api/market-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsIngestRoute = ApiNewsIngestRouteImport.update({
  id: '/api/news-ingest',
  path: '/api/news-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsIngestV2Route = ApiNewsIngestV2RouteImport.update({
  id: '/api/news-ingest-v2',
  path: '/api/news-ingest-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramPhotoRoute = ApiTelegramPhotoRouteImport.update({
  id: '/api/telegram-photo',
  path: '/api/telegram-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramVideoRoute = ApiTelegramVideoRouteImport.update({
  id: '/api/telegram-video',
  path: '/api/telegram-video',
  getParentRoute: () => rootRouteImport,
} as any)
const NSlugRoute = NSlugRouteImport.update({
  id: '/n/$slug',
  path: '/n/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsIdRoute = ApiNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/markets': typeof MarketsRoute
  '/api/market-prices': typeof ApiMarketPricesRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/news-ingest': typeof ApiNewsIngestRoute
  '/api/news-ingest-v2': typeof ApiNewsIngestV2Route
  '/api/telegram-photo': typeof ApiTelegramPhotoRoute
  '/api/telegram-video': typeof ApiTelegramVideoRoute
  '/n/$slug': typeof NSlugRoute
  '/api/news/$id': typeof ApiNewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/markets': typeof MarketsRoute
  '/api/market-prices': typeof ApiMarketPricesRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/news-ingest': typeof ApiNewsIngestRoute
  '/api/news-ingest-v2': typeof ApiNewsIngestV2Route
  '/api/telegram-photo': typeof ApiTelegramPhotoRoute
  '/api/telegram-video': typeof ApiTelegramVideoRoute
  '/n/$slug': typeof NSlugRoute
  '/api/news/$id': typeof ApiNewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/markets': typeof MarketsRoute
  '/api/market-prices': typeof ApiMarketPricesRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/news-ingest': typeof ApiNewsIngestRoute
  '/api/news-ingest-v2': typeof ApiNewsIngestV2Route
  '/api/telegram-photo': typeof ApiTelegramPhotoRoute
  '/api/telegram-video': typeof ApiTelegramVideoRoute
  '/n/$slug': typeof NSlugRoute
  '/api/news/$id': typeof ApiNewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/markets'
    | '/api/market-prices'
    | '/api/news'
    | '/api/news-ingest'
    | '/api/news-ingest-v2'
    | '/api/telegram-photo'
    | '/api/telegram-video'
    | '/n/$slug'
    | '/api/news/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/markets'
    | '/api/market-prices'
    | '/api/news'
    | '/api/news-ingest'
    | '/api/news-ingest-v2'
    | '/api/telegram-photo'
    | '/api/telegram-video'
    | '/n/$slug'
    | '/api/news/$id'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/markets'
    | '/api/market-prices'
    | '/api/news'
    | '/api/news-ingest'
    | '/api/news-ingest-v2'
    | '/api/telegram-photo'
    | '/api/telegram-video'
    | '/n/$slug'
    | '/api/news/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  MarketsRoute: typeof MarketsRoute
  ApiMarketPricesRoute: typeof ApiMarketPricesRoute
  ApiNewsRoute: typeof ApiNewsRouteWithChildren
  ApiNewsIngestRoute: typeof ApiNewsIngestRoute
  ApiNewsIngestV2Route: typeof ApiNewsIngestV2Route
  ApiTelegramPhotoRoute: typeof ApiTelegramPhotoRoute
  ApiTelegramVideoRoute: typeof ApiTelegramVideoRoute
  NSlugRoute: typeof NSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-prices': {
      id: '/api/market-prices'
      path: '/api/market-prices'
      fullPath: '/api/market-prices'
      preLoaderRoute: typeof ApiMarketPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news-ingest': {
      id: '/api/news-ingest'
      path: '/api/news-ingest'
      fullPath: '/api/news-ingest'
      preLoaderRoute: typeof ApiNewsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news-ingest-v2': {
      id: '/api/news-ingest-v2'
      path: '/api/news-ingest-v2'
      fullPath: '/api/news-ingest-v2'
      preLoaderRoute: typeof ApiNewsIngestV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-photo': {
      id: '/api/telegram-photo'
      path: '/api/telegram-photo'
      fullPath: '/api/telegram-photo'
      preLoaderRoute: typeof ApiTelegramPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-video': {
      id: '/api/telegram-video'
      path: '/api/telegram-video'
      fullPath: '/api/telegram-video'
      preLoaderRoute: typeof ApiTelegramVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$slug': {
      id: '/n/$slug'
      path: '/n/$slug'
      fullPath: '/n/$slug'
      preLoaderRoute: typeof NSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/$id': {
      id: '/api/news/$id'
      path: '/$id'
      fullPath: '/api/news/$id'
      preLoaderRoute: typeof ApiNewsIdRouteImport
      parentRoute: typeof ApiNewsRoute
    }
  }
}

interface ApiNewsRouteChildren {
  ApiNewsIdRoute: typeof ApiNewsIdRoute
}

const ApiNewsRouteChildren: ApiNewsRouteChildren = {
  ApiNewsIdRoute: ApiNewsIdRoute,
}

const ApiNewsRouteWithChildren =
  ApiNewsRoute._addFileChildren(ApiNewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  MarketsRoute: MarketsRoute,
  ApiMarketPricesRoute: ApiMarketPricesRoute,
  ApiNewsRoute: ApiNewsRouteWithChildren,
  ApiNewsIngestRoute: ApiNewsIngestRoute,
  ApiNewsIngestV2Route: ApiNewsIngestV2Route,
  ApiTelegramPhotoRoute: ApiTelegramPhotoRoute,
  ApiTelegramVideoRoute: ApiTelegramVideoRoute,
  NSlugRoute: NSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
